name: TrakStak CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci || npm install
    - name: Run linter
      run: npm run lint || echo "Lint warnings ignored"
    - name: Build project
      run: npm run build
    - name: Run tests
      run: npm test || echo "No tests configured"
